// Model pricing data - prices are per 1 million tokens
// Updated: March 2026

export const MODEL_DATA_LAST_UPDATED = '2026-03-05'

export type ModelProvider =
  | 'openai' | 'anthropic' | 'google' | 'azure' | 'ollama' | 'groq'
  | 'deepseek' | 'qwen' | 'mistral' | 'zhipu' | 'moonshot' | 'minimax'
  | 'yi' | 'bedrock' | 'meta' | 'xai' | 'cohere' | 'amazon' | 'perplexity' | 'other'

export interface ModelPricing {
  name: string
  provider: ModelProvider
  displayName: string
  inputPrice: number // per 1M tokens
  outputPrice: number // per 1M tokens
  contextWindow: number
  capabilityTier: 'low' | 'medium' | 'high'
  supportsVision?: boolean
  supportsFunctionCalling?: boolean
  benchmarkScores?: {
    mmlu?: number        // 0-100
    humanEval?: number   // 0-100
    math?: number        // 0-100
    chatbotArena?: number // ELO rating
  }
}

export const modelPricing: ModelPricing[] = [
  // ============ OpenAI ============
  {
    name: 'gpt-4.1',
    provider: 'openai',
    displayName: 'GPT-4.1',
    inputPrice: 2.00,
    outputPrice: 8.00,
    contextWindow: 1000000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gpt-4.1-mini',
    provider: 'openai',
    displayName: 'GPT-4.1 Mini',
    inputPrice: 0.40,
    outputPrice: 1.60,
    contextWindow: 1000000,
    capabilityTier: 'medium',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gpt-4.1-nano',
    provider: 'openai',
    displayName: 'GPT-4.1 Nano',
    inputPrice: 0.10,
    outputPrice: 0.40,
    contextWindow: 1000000,
    capabilityTier: 'low',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gpt-4o',
    provider: 'openai',
    displayName: 'GPT-4o',
    inputPrice: 2.50,
    outputPrice: 10.00,
    contextWindow: 128000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gpt-4o-mini',
    provider: 'openai',
    displayName: 'GPT-4o Mini',
    inputPrice: 0.15,
    outputPrice: 0.60,
    contextWindow: 128000,
    capabilityTier: 'medium',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'o3',
    provider: 'openai',
    displayName: 'o3',
    inputPrice: 10.00,
    outputPrice: 40.00,
    contextWindow: 200000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'o3-mini',
    provider: 'openai',
    displayName: 'o3 Mini',
    inputPrice: 1.10,
    outputPrice: 4.40,
    contextWindow: 200000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'o1',
    provider: 'openai',
    displayName: 'o1',
    inputPrice: 15.00,
    outputPrice: 60.00,
    contextWindow: 200000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'o1-mini',
    provider: 'openai',
    displayName: 'o1 Mini',
    inputPrice: 3.00,
    outputPrice: 12.00,
    contextWindow: 128000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'gpt-5',
    provider: 'openai',
    displayName: 'GPT-5',
    inputPrice: 1.25,
    outputPrice: 10.00,
    contextWindow: 400000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gpt-5-mini',
    provider: 'openai',
    displayName: 'GPT-5 Mini',
    inputPrice: 0.25,
    outputPrice: 2.00,
    contextWindow: 400000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gpt-5-pro',
    provider: 'openai',
    displayName: 'GPT-5 Pro',
    inputPrice: 15.00,
    outputPrice: 120.00,
    contextWindow: 400000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gpt-5.1-codex',
    provider: 'openai',
    displayName: 'GPT-5.1 Codex',
    inputPrice: 1.25,
    outputPrice: 10.00,
    contextWindow: 400000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gpt-5.2-pro',
    provider: 'openai',
    displayName: 'GPT-5.2 Pro',
    inputPrice: 1.75,
    outputPrice: 14.00,
    contextWindow: 400000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gpt-5.2-chat',
    provider: 'openai',
    displayName: 'GPT-5.2 Chat',
    inputPrice: 1.25,
    outputPrice: 10.00,
    contextWindow: 400000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gpt-5.3-chat',
    provider: 'openai',
    displayName: 'GPT-5.3 Chat',
    inputPrice: 1.75,
    outputPrice: 14.00,
    contextWindow: 128000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'o4-mini',
    provider: 'openai',
    displayName: 'o4 Mini',
    inputPrice: 1.10,
    outputPrice: 4.40,
    contextWindow: 200000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },

  // ============ Anthropic ============
  {
    name: 'claude-opus-4-20250514',
    provider: 'anthropic',
    displayName: 'Claude Opus 4',
    inputPrice: 15.00,
    outputPrice: 75.00,
    contextWindow: 200000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'claude-sonnet-4-20250514',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 4',
    inputPrice: 3.00,
    outputPrice: 15.00,
    contextWindow: 200000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'claude-3-5-sonnet-20241022',
    provider: 'anthropic',
    displayName: 'Claude 3.5 Sonnet',
    inputPrice: 3.00,
    outputPrice: 15.00,
    contextWindow: 200000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'claude-3-5-haiku-20241022',
    provider: 'anthropic',
    displayName: 'Claude 3.5 Haiku',
    inputPrice: 0.80,
    outputPrice: 4.00,
    contextWindow: 200000,
    capabilityTier: 'medium',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'claude-3-7-sonnet-20250219',
    provider: 'anthropic',
    displayName: 'Claude 3.7 Sonnet',
    inputPrice: 3.00,
    outputPrice: 15.00,
    contextWindow: 200000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'claude-3-opus-20240229',
    provider: 'anthropic',
    displayName: 'Claude 3 Opus',
    inputPrice: 15.00,
    outputPrice: 75.00,
    contextWindow: 200000,
    capabilityTier: 'high',
    supportsVision: true,
  },

  // ============ Google ============
  {
    name: 'gemini-2.5-pro',
    provider: 'google',
    displayName: 'Gemini 2.5 Pro',
    inputPrice: 1.25,
    outputPrice: 10.00,
    contextWindow: 1000000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gemini-2.5-flash',
    provider: 'google',
    displayName: 'Gemini 2.5 Flash',
    inputPrice: 0.15,
    outputPrice: 0.60,
    contextWindow: 1000000,
    capabilityTier: 'medium',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gemini-2.0-flash',
    provider: 'google',
    displayName: 'Gemini 2.0 Flash',
    inputPrice: 0.10,
    outputPrice: 0.40,
    contextWindow: 1000000,
    capabilityTier: 'medium',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gemini-2.0-flash-lite',
    provider: 'google',
    displayName: 'Gemini 2.0 Flash Lite',
    inputPrice: 0.075,
    outputPrice: 0.30,
    contextWindow: 1000000,
    capabilityTier: 'low',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gemini-1.5-pro',
    provider: 'google',
    displayName: 'Gemini 1.5 Pro',
    inputPrice: 1.25,
    outputPrice: 5.00,
    contextWindow: 2000000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gemini-1.5-flash',
    provider: 'google',
    displayName: 'Gemini 1.5 Flash',
    inputPrice: 0.075,
    outputPrice: 0.30,
    contextWindow: 1000000,
    capabilityTier: 'medium',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gemini-3-pro',
    provider: 'google',
    displayName: 'Gemini 3 Pro',
    inputPrice: 2.00,
    outputPrice: 12.00,
    contextWindow: 1048576,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gemini-3-flash',
    provider: 'google',
    displayName: 'Gemini 3 Flash',
    inputPrice: 0.50,
    outputPrice: 3.00,
    contextWindow: 1048576,
    capabilityTier: 'medium',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gemini-3.1-pro',
    provider: 'google',
    displayName: 'Gemini 3.1 Pro',
    inputPrice: 2.00,
    outputPrice: 12.00,
    contextWindow: 1048576,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gemini-3.1-flash',
    provider: 'google',
    displayName: 'Gemini 3.1 Flash',
    inputPrice: 0.50,
    outputPrice: 3.00,
    contextWindow: 1048576,
    capabilityTier: 'medium',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'gemini-3.1-flash-lite',
    provider: 'google',
    displayName: 'Gemini 3.1 Flash Lite',
    inputPrice: 0.10,
    outputPrice: 0.40,
    contextWindow: 262144,
    capabilityTier: 'low',
    supportsVision: true,
    supportsFunctionCalling: true,
  },

  // ============ DeepSeek ============
  {
    name: 'deepseek-r1',
    provider: 'deepseek',
    displayName: 'DeepSeek R1',
    inputPrice: 0.55,
    outputPrice: 2.19,
    contextWindow: 128000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'deepseek-v3',
    provider: 'deepseek',
    displayName: 'DeepSeek V3',
    inputPrice: 0.27,
    outputPrice: 1.10,
    contextWindow: 128000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'deepseek-chat',
    provider: 'deepseek',
    displayName: 'DeepSeek Chat',
    inputPrice: 0.14,
    outputPrice: 0.28,
    contextWindow: 128000,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'deepseek-coder',
    provider: 'deepseek',
    displayName: 'DeepSeek Coder',
    inputPrice: 0.14,
    outputPrice: 0.28,
    contextWindow: 128000,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'deepseek-v3.1',
    provider: 'deepseek',
    displayName: 'DeepSeek V3.1',
    inputPrice: 0.21,
    outputPrice: 0.79,
    contextWindow: 163840,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'deepseek-v3.2',
    provider: 'deepseek',
    displayName: 'DeepSeek V3.2',
    inputPrice: 0.25,
    outputPrice: 0.80,
    contextWindow: 163840,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'deepseek-r1t2-chimera',
    provider: 'deepseek',
    displayName: 'DeepSeek R1T2 Chimera',
    inputPrice: 0.25,
    outputPrice: 0.80,
    contextWindow: 163840,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },

  // ============ Qwen (Alibaba) ============
  {
    name: 'qwen-max',
    provider: 'qwen',
    displayName: 'Qwen Max',
    inputPrice: 1.60,
    outputPrice: 6.40,
    contextWindow: 32000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'qwen-plus',
    provider: 'qwen',
    displayName: 'Qwen Plus',
    inputPrice: 0.80,
    outputPrice: 2.00,
    contextWindow: 131072,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'qwen-turbo',
    provider: 'qwen',
    displayName: 'Qwen Turbo',
    inputPrice: 0.30,
    outputPrice: 0.60,
    contextWindow: 131072,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'qwen-long',
    provider: 'qwen',
    displayName: 'Qwen Long',
    inputPrice: 0.14,
    outputPrice: 0.28,
    contextWindow: 10000000,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'qwen2.5-72b-instruct',
    provider: 'qwen',
    displayName: 'Qwen 2.5 72B',
    inputPrice: 0.90,
    outputPrice: 0.90,
    contextWindow: 131072,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'qwen2.5-coder-32b',
    provider: 'qwen',
    displayName: 'Qwen 2.5 Coder 32B',
    inputPrice: 0.60,
    outputPrice: 0.60,
    contextWindow: 131072,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'qwen3-235b-a22b',
    provider: 'qwen',
    displayName: 'Qwen3 235B',
    inputPrice: 0.46,
    outputPrice: 1.82,
    contextWindow: 131072,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'qwen3-30b-a3b',
    provider: 'qwen',
    displayName: 'Qwen3 30B A3B',
    inputPrice: 0.05,
    outputPrice: 0.40,
    contextWindow: 131072,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'qwen3-coder',
    provider: 'qwen',
    displayName: 'Qwen3 Coder 480B',
    inputPrice: 0.22,
    outputPrice: 1.80,
    contextWindow: 262144,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'qwen3.5-72b',
    provider: 'qwen',
    displayName: 'Qwen3.5 72B',
    inputPrice: 0.16,
    outputPrice: 1.30,
    contextWindow: 262144,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'qwen3.5-27b',
    provider: 'qwen',
    displayName: 'Qwen3.5 27B',
    inputPrice: 0.20,
    outputPrice: 1.56,
    contextWindow: 262144,
    capabilityTier: 'medium',
    supportsVision: true,
    supportsFunctionCalling: true,
  },

  // ============ Mistral AI ============
  {
    name: 'mistral-large-latest',
    provider: 'mistral',
    displayName: 'Mistral Large',
    inputPrice: 2.00,
    outputPrice: 6.00,
    contextWindow: 128000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'mistral-medium-latest',
    provider: 'mistral',
    displayName: 'Mistral Medium',
    inputPrice: 0.80,
    outputPrice: 2.40,
    contextWindow: 128000,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'mistral-small-latest',
    provider: 'mistral',
    displayName: 'Mistral Small',
    inputPrice: 0.20,
    outputPrice: 0.60,
    contextWindow: 128000,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'codestral-latest',
    provider: 'mistral',
    displayName: 'Codestral',
    inputPrice: 0.30,
    outputPrice: 0.90,
    contextWindow: 256000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'pixtral-large-latest',
    provider: 'mistral',
    displayName: 'Pixtral Large',
    inputPrice: 2.00,
    outputPrice: 6.00,
    contextWindow: 128000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'ministral-8b-latest',
    provider: 'mistral',
    displayName: 'Ministral 8B',
    inputPrice: 0.10,
    outputPrice: 0.10,
    contextWindow: 128000,
    capabilityTier: 'low',
    supportsFunctionCalling: true,
  },
  {
    name: 'mistral-medium-3',
    provider: 'mistral',
    displayName: 'Mistral Medium 3',
    inputPrice: 0.40,
    outputPrice: 2.00,
    contextWindow: 131072,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'mistral-small-3.2',
    provider: 'mistral',
    displayName: 'Mistral Small 3.2',
    inputPrice: 0.10,
    outputPrice: 0.30,
    contextWindow: 128000,
    capabilityTier: 'medium',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'codestral-2508',
    provider: 'mistral',
    displayName: 'Codestral 25.08',
    inputPrice: 0.30,
    outputPrice: 0.90,
    contextWindow: 256000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },

  // ============ Zhipu (GLM) ============
  {
    name: 'glm-4-plus',
    provider: 'zhipu',
    displayName: 'GLM-4 Plus',
    inputPrice: 1.40,
    outputPrice: 1.40,
    contextWindow: 128000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'glm-4',
    provider: 'zhipu',
    displayName: 'GLM-4',
    inputPrice: 0.70,
    outputPrice: 0.70,
    contextWindow: 128000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'glm-4-flash',
    provider: 'zhipu',
    displayName: 'GLM-4 Flash',
    inputPrice: 0.01,
    outputPrice: 0.01,
    contextWindow: 128000,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'glm-4-long',
    provider: 'zhipu',
    displayName: 'GLM-4 Long',
    inputPrice: 0.14,
    outputPrice: 0.14,
    contextWindow: 1000000,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'glm-4v-plus',
    provider: 'zhipu',
    displayName: 'GLM-4V Plus',
    inputPrice: 1.40,
    outputPrice: 1.40,
    contextWindow: 8192,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },

  // ============ Moonshot (Kimi) ============
  {
    name: 'moonshot-v1-128k',
    provider: 'moonshot',
    displayName: 'Kimi 128K',
    inputPrice: 0.84,
    outputPrice: 0.84,
    contextWindow: 128000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'moonshot-v1-32k',
    provider: 'moonshot',
    displayName: 'Kimi 32K',
    inputPrice: 0.34,
    outputPrice: 0.34,
    contextWindow: 32000,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'moonshot-v1-8k',
    provider: 'moonshot',
    displayName: 'Kimi 8K',
    inputPrice: 0.17,
    outputPrice: 0.17,
    contextWindow: 8192,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },

  // ============ MiniMax ============
  {
    name: 'abab6.5s-chat',
    provider: 'minimax',
    displayName: 'MiniMax abab 6.5s',
    inputPrice: 0.14,
    outputPrice: 0.14,
    contextWindow: 245760,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'abab6.5-chat',
    provider: 'minimax',
    displayName: 'MiniMax abab 6.5',
    inputPrice: 0.42,
    outputPrice: 0.42,
    contextWindow: 8192,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'abab5.5-chat',
    provider: 'minimax',
    displayName: 'MiniMax abab 5.5',
    inputPrice: 0.21,
    outputPrice: 0.21,
    contextWindow: 6144,
    capabilityTier: 'low',
  },

  // ============ 01.AI (Yi) ============
  {
    name: 'yi-large',
    provider: 'yi',
    displayName: 'Yi Large',
    inputPrice: 2.50,
    outputPrice: 2.50,
    contextWindow: 32000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'yi-medium',
    provider: 'yi',
    displayName: 'Yi Medium',
    inputPrice: 0.36,
    outputPrice: 0.36,
    contextWindow: 16000,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
  {
    name: 'yi-spark',
    provider: 'yi',
    displayName: 'Yi Spark',
    inputPrice: 0.14,
    outputPrice: 0.14,
    contextWindow: 16000,
    capabilityTier: 'low',
    supportsFunctionCalling: true,
  },
  {
    name: 'yi-large-turbo',
    provider: 'yi',
    displayName: 'Yi Large Turbo',
    inputPrice: 1.70,
    outputPrice: 1.70,
    contextWindow: 16000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },

  // ============ Groq ============
  {
    name: 'llama-3.3-70b-versatile',
    provider: 'groq',
    displayName: 'Llama 3.3 70B Versatile',
    inputPrice: 0.59,
    outputPrice: 0.79,
    contextWindow: 128000,
    capabilityTier: 'high',
  },
  {
    name: 'llama-3.1-8b-instant',
    provider: 'groq',
    displayName: 'Llama 3.1 8B Instant',
    inputPrice: 0.05,
    outputPrice: 0.08,
    contextWindow: 128000,
    capabilityTier: 'low',
  },
  {
    name: 'mixtral-8x7b-32768',
    provider: 'groq',
    displayName: 'Mixtral 8x7B',
    inputPrice: 0.24,
    outputPrice: 0.24,
    contextWindow: 32768,
    capabilityTier: 'medium',
  },
  {
    name: 'gemma2-9b-it',
    provider: 'groq',
    displayName: 'Gemma 2 9B',
    inputPrice: 0.20,
    outputPrice: 0.20,
    contextWindow: 8192,
    capabilityTier: 'low',
  },

  // ============ Azure OpenAI ============
  {
    name: 'azure-gpt-4o',
    provider: 'azure',
    displayName: 'Azure GPT-4o',
    inputPrice: 2.50,
    outputPrice: 10.00,
    contextWindow: 128000,
    capabilityTier: 'high',
    supportsVision: true,
  },
  {
    name: 'azure-gpt-4o-mini',
    provider: 'azure',
    displayName: 'Azure GPT-4o Mini',
    inputPrice: 0.15,
    outputPrice: 0.60,
    contextWindow: 128000,
    capabilityTier: 'medium',
  },
  {
    name: 'azure-gpt-4.1',
    provider: 'azure',
    displayName: 'Azure GPT-4.1',
    inputPrice: 2.00,
    outputPrice: 8.00,
    contextWindow: 1000000,
    capabilityTier: 'high',
    supportsVision: true,
  },

  // ============ AWS Bedrock ============
  {
    name: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    provider: 'bedrock',
    displayName: 'Claude 3.5 Sonnet (Bedrock)',
    inputPrice: 3.00,
    outputPrice: 15.00,
    contextWindow: 200000,
    capabilityTier: 'high',
    supportsVision: true,
  },
  {
    name: 'anthropic.claude-3-haiku-20240307-v1:0',
    provider: 'bedrock',
    displayName: 'Claude 3 Haiku (Bedrock)',
    inputPrice: 0.25,
    outputPrice: 1.25,
    contextWindow: 200000,
    capabilityTier: 'low',
  },
  {
    name: 'amazon.nova-pro-v1:0',
    provider: 'bedrock',
    displayName: 'Amazon Nova Pro',
    inputPrice: 0.80,
    outputPrice: 3.20,
    contextWindow: 300000,
    capabilityTier: 'high',
    supportsVision: true,
  },
  {
    name: 'amazon.nova-lite-v1:0',
    provider: 'bedrock',
    displayName: 'Amazon Nova Lite',
    inputPrice: 0.06,
    outputPrice: 0.24,
    contextWindow: 300000,
    capabilityTier: 'medium',
    supportsVision: true,
  },
  {
    name: 'meta.llama3-1-70b-instruct-v1:0',
    provider: 'bedrock',
    displayName: 'Llama 3.1 70B (Bedrock)',
    inputPrice: 0.72,
    outputPrice: 0.72,
    contextWindow: 128000,
    capabilityTier: 'high',
  },

  // ============ Meta (Llama) ============
  {
    name: 'llama-4-maverick',
    provider: 'meta',
    displayName: 'Llama 4 Maverick',
    inputPrice: 0.25,
    outputPrice: 1.00,
    contextWindow: 1048576,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'llama-4-scout',
    provider: 'meta',
    displayName: 'Llama 4 Scout',
    inputPrice: 0.08,
    outputPrice: 0.30,
    contextWindow: 327680,
    capabilityTier: 'medium',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'llama-3.3-70b-instruct',
    provider: 'meta',
    displayName: 'Llama 3.3 70B',
    inputPrice: 0.40,
    outputPrice: 0.40,
    contextWindow: 131072,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'llama-3.1-405b-instruct',
    provider: 'meta',
    displayName: 'Llama 3.1 405B',
    inputPrice: 4.00,
    outputPrice: 4.00,
    contextWindow: 131000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'llama-3.1-70b-instruct',
    provider: 'meta',
    displayName: 'Llama 3.1 70B',
    inputPrice: 0.40,
    outputPrice: 0.40,
    contextWindow: 131072,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },

  // ============ xAI (Grok) ============
  {
    name: 'grok-4',
    provider: 'xai',
    displayName: 'Grok 4',
    inputPrice: 3.00,
    outputPrice: 15.00,
    contextWindow: 256000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'grok-4-fast',
    provider: 'xai',
    displayName: 'Grok 4 Fast',
    inputPrice: 0.20,
    outputPrice: 1.00,
    contextWindow: 2000000,
    capabilityTier: 'high',
    supportsVision: true,
    supportsFunctionCalling: true,
  },
  {
    name: 'grok-3-mini',
    provider: 'xai',
    displayName: 'Grok 3 Mini',
    inputPrice: 0.30,
    outputPrice: 0.50,
    contextWindow: 131072,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },

  // ============ Cohere ============
  {
    name: 'command-a-03-2025',
    provider: 'cohere',
    displayName: 'Command A',
    inputPrice: 2.50,
    outputPrice: 10.00,
    contextWindow: 256000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'command-r-plus',
    provider: 'cohere',
    displayName: 'Command R+',
    inputPrice: 2.50,
    outputPrice: 10.00,
    contextWindow: 128000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'command-r7b',
    provider: 'cohere',
    displayName: 'Command R7B',
    inputPrice: 0.04,
    outputPrice: 0.15,
    contextWindow: 128000,
    capabilityTier: 'low',
    supportsFunctionCalling: true,
  },

  // ============ Perplexity ============
  {
    name: 'sonar-pro',
    provider: 'perplexity',
    displayName: 'Sonar Pro',
    inputPrice: 3.00,
    outputPrice: 15.00,
    contextWindow: 200000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'sonar-reasoning-pro',
    provider: 'perplexity',
    displayName: 'Sonar Reasoning Pro',
    inputPrice: 3.00,
    outputPrice: 15.00,
    contextWindow: 200000,
    capabilityTier: 'high',
    supportsFunctionCalling: true,
  },
  {
    name: 'sonar',
    provider: 'perplexity',
    displayName: 'Sonar',
    inputPrice: 1.00,
    outputPrice: 1.00,
    contextWindow: 127072,
    capabilityTier: 'medium',
    supportsFunctionCalling: true,
  },
]

// Helper to get pricing by model name
export function getModelPricing(modelName: string): ModelPricing | undefined {
  return modelPricing.find(m => m.name.toLowerCase() === modelName.toLowerCase())
}

// Helper to calculate cost
export function calculateCost(
  modelName: string,
  promptTokens: number,
  completionTokens: number
): number {
  const pricing = getModelPricing(modelName)
  if (!pricing) return 0

  const promptCost = (promptTokens / 1_000_000) * pricing.inputPrice
  const completionCost = (completionTokens / 1_000_000) * pricing.outputPrice

  return promptCost + completionCost
}

// Get models by provider
export function getModelsByProvider(provider: string): ModelPricing[] {
  return modelPricing.filter(m => m.provider === provider)
}

// Get models by capability tier
export function getModelsByTier(tier: 'low' | 'medium' | 'high'): ModelPricing[] {
  return modelPricing.filter(m => m.capabilityTier === tier)
}

// Get cheaper alternatives for a model
export function getCheaperAlternatives(modelName: string): ModelPricing[] {
  const current = getModelPricing(modelName)
  if (!current) return []

  // Find models with lower or equal capability tier
  const tierOrder = { low: 0, medium: 1, high: 2 }
  const currentTier = tierOrder[current.capabilityTier]

  return modelPricing
    .filter(m =>
      m.name !== current.name &&
      tierOrder[m.capabilityTier] <= currentTier
    )
    .sort((a, b) => (a.inputPrice + a.outputPrice) - (b.inputPrice + b.outputPrice))
    .slice(0, 3)
}

// ============ Public Benchmark Scores ============
// Curated from public sources: Chatbot Arena, MMLU, HumanEval, MATH
// Last updated: March 2026
export interface PublicBenchmark {
  model: string
  displayName: string
  provider: string
  chatbotArena?: number  // ELO rating
  mmlu?: number          // 0-100 accuracy
  humanEval?: number     // 0-100 pass@1
  math?: number          // 0-100 accuracy
  gpqa?: number          // 0-100 accuracy
}

export const publicBenchmarks: PublicBenchmark[] = [
  // OpenAI
  { model: 'gpt-4.1', displayName: 'GPT-4.1', provider: 'openai', chatbotArena: 1380, mmlu: 90.2, humanEval: 92.0, math: 82.5, gpqa: 56.1 },
  { model: 'gpt-4.1-mini', displayName: 'GPT-4.1 Mini', provider: 'openai', chatbotArena: 1320, mmlu: 87.5, humanEval: 87.2, math: 76.0, gpqa: 49.3 },
  { model: 'gpt-4.1-nano', displayName: 'GPT-4.1 Nano', provider: 'openai', chatbotArena: 1250, mmlu: 80.1, humanEval: 78.5, math: 62.4 },
  { model: 'gpt-4o', displayName: 'GPT-4o', provider: 'openai', chatbotArena: 1340, mmlu: 88.7, humanEval: 90.2, math: 76.6, gpqa: 53.6 },
  { model: 'gpt-4o-mini', displayName: 'GPT-4o Mini', provider: 'openai', chatbotArena: 1275, mmlu: 82.0, humanEval: 87.0, math: 70.2 },
  { model: 'o3', displayName: 'o3', provider: 'openai', chatbotArena: 1415, mmlu: 92.3, humanEval: 96.7, math: 96.7, gpqa: 87.7 },
  { model: 'o3-mini', displayName: 'o3 Mini', provider: 'openai', chatbotArena: 1370, mmlu: 86.9, humanEval: 92.6, math: 90.0, gpqa: 79.6 },
  { model: 'o1', displayName: 'o1', provider: 'openai', chatbotArena: 1352, mmlu: 91.8, humanEval: 94.4, math: 94.8, gpqa: 78.0 },
  { model: 'gpt-5', displayName: 'GPT-5', provider: 'openai', chatbotArena: 1430, mmlu: 93.0, humanEval: 96.2, math: 90.5, gpqa: 70.2 },
  { model: 'gpt-5-mini', displayName: 'GPT-5 Mini', provider: 'openai', chatbotArena: 1385, mmlu: 89.5, humanEval: 91.8, math: 82.0, gpqa: 58.3 },
  { model: 'gpt-5.2-pro', displayName: 'GPT-5.2 Pro', provider: 'openai', chatbotArena: 1445, mmlu: 94.1, humanEval: 97.0, math: 92.0, gpqa: 73.5 },
  { model: 'o4-mini', displayName: 'o4 Mini', provider: 'openai', chatbotArena: 1390, mmlu: 88.2, humanEval: 93.5, math: 91.0, gpqa: 80.1 },
  // Anthropic
  { model: 'claude-opus-4-20250514', displayName: 'Claude Opus 4', provider: 'anthropic', chatbotArena: 1410, mmlu: 91.5, humanEval: 95.2, math: 83.5, gpqa: 60.4 },
  { model: 'claude-sonnet-4-20250514', displayName: 'Claude Sonnet 4', provider: 'anthropic', chatbotArena: 1395, mmlu: 90.4, humanEval: 93.7, math: 81.1, gpqa: 59.4 },
  { model: 'claude-3-7-sonnet-20250219', displayName: 'Claude 3.7 Sonnet', provider: 'anthropic', chatbotArena: 1310, mmlu: 89.5, humanEval: 92.8, math: 79.5, gpqa: 59.8 },
  { model: 'claude-3-5-sonnet-20241022', displayName: 'Claude 3.5 Sonnet', provider: 'anthropic', chatbotArena: 1268, mmlu: 88.7, humanEval: 92.0, math: 78.3, gpqa: 59.4 },
  { model: 'claude-3-5-haiku-20241022', displayName: 'Claude 3.5 Haiku', provider: 'anthropic', chatbotArena: 1188, mmlu: 77.1, humanEval: 88.1, math: 69.2 },
  // Google
  { model: 'gemini-2.5-pro', displayName: 'Gemini 2.5 Pro', provider: 'google', chatbotArena: 1405, mmlu: 91.8, humanEval: 94.5, math: 86.2, gpqa: 63.0 },
  { model: 'gemini-2.5-flash', displayName: 'Gemini 2.5 Flash', provider: 'google', chatbotArena: 1351, mmlu: 86.2, humanEval: 89.3, math: 78.8, gpqa: 52.1 },
  { model: 'gemini-2.0-flash', displayName: 'Gemini 2.0 Flash', provider: 'google', chatbotArena: 1305, mmlu: 83.5, humanEval: 85.0, math: 73.4 },
  { model: 'gemini-3-pro', displayName: 'Gemini 3 Pro', provider: 'google', chatbotArena: 1440, mmlu: 93.5, humanEval: 96.0, math: 88.5, gpqa: 66.0 },
  { model: 'gemini-3-flash', displayName: 'Gemini 3 Flash', provider: 'google', chatbotArena: 1380, mmlu: 88.0, humanEval: 91.0, math: 80.2, gpqa: 54.5 },
  { model: 'gemini-3.1-pro', displayName: 'Gemini 3.1 Pro', provider: 'google', chatbotArena: 1450, mmlu: 94.0, humanEval: 96.5, math: 89.0, gpqa: 67.5 },
  // DeepSeek
  { model: 'deepseek-r1', displayName: 'DeepSeek R1', provider: 'deepseek', chatbotArena: 1358, mmlu: 90.8, humanEval: 92.8, math: 97.3, gpqa: 71.5 },
  { model: 'deepseek-v3', displayName: 'DeepSeek V3', provider: 'deepseek', chatbotArena: 1318, mmlu: 88.5, humanEval: 89.4, math: 75.9, gpqa: 59.1 },
  { model: 'deepseek-v3.1', displayName: 'DeepSeek V3.1', provider: 'deepseek', chatbotArena: 1345, mmlu: 89.8, humanEval: 91.0, math: 78.5, gpqa: 62.0 },
  { model: 'deepseek-v3.2', displayName: 'DeepSeek V3.2', provider: 'deepseek', chatbotArena: 1360, mmlu: 90.5, humanEval: 92.5, math: 80.3, gpqa: 64.0 },
  // Qwen
  { model: 'qwen-max', displayName: 'Qwen Max', provider: 'qwen', chatbotArena: 1290, mmlu: 86.2, humanEval: 86.0, math: 71.8 },
  { model: 'qwen-plus', displayName: 'Qwen Plus', provider: 'qwen', chatbotArena: 1245, mmlu: 83.8, humanEval: 82.4, math: 66.5 },
  { model: 'qwen3-235b-a22b', displayName: 'Qwen3 235B', provider: 'qwen', chatbotArena: 1370, mmlu: 89.5, humanEval: 93.0, math: 82.0, gpqa: 61.5 },
  { model: 'qwen3.5-72b', displayName: 'Qwen3.5 72B', provider: 'qwen', chatbotArena: 1385, mmlu: 90.0, humanEval: 93.5, math: 84.0, gpqa: 63.0 },
  // Mistral
  { model: 'mistral-large-latest', displayName: 'Mistral Large', provider: 'mistral', chatbotArena: 1265, mmlu: 84.0, humanEval: 84.7, math: 69.4 },
  { model: 'mistral-medium-latest', displayName: 'Mistral Medium', provider: 'mistral', chatbotArena: 1220, mmlu: 80.5, humanEval: 79.2, math: 63.1 },
  { model: 'mistral-medium-3', displayName: 'Mistral Medium 3', provider: 'mistral', chatbotArena: 1300, mmlu: 85.0, humanEval: 87.0, math: 72.5 },
  // xAI
  { model: 'grok-4', displayName: 'Grok 4', provider: 'xai', chatbotArena: 1420, mmlu: 92.0, humanEval: 95.5, math: 88.0, gpqa: 68.0 },
  { model: 'grok-4-fast', displayName: 'Grok 4 Fast', provider: 'xai', chatbotArena: 1380, mmlu: 88.5, humanEval: 91.0, math: 80.0, gpqa: 58.5 },
  // Meta
  { model: 'llama-4-maverick', displayName: 'Llama 4 Maverick', provider: 'meta', chatbotArena: 1340, mmlu: 88.0, humanEval: 89.5, math: 76.0, gpqa: 55.0 },
  { model: 'llama-4-scout', displayName: 'Llama 4 Scout', provider: 'meta', chatbotArena: 1280, mmlu: 83.5, humanEval: 84.0, math: 68.5 },
  // Other
  { model: 'glm-4-plus', displayName: 'GLM-4 Plus', provider: 'zhipu', chatbotArena: 1215, mmlu: 82.3, humanEval: 78.0, math: 64.2 },
  { model: 'yi-large', displayName: 'Yi Large', provider: 'yi', chatbotArena: 1210, mmlu: 81.5, humanEval: 79.7, math: 62.1 },
]
